version: "3.3"

networks:
  test-network:
    driver: bridge

services:

  seleniumgrid:
    image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210823      
    ports:
      - "4444:4444"
    networks:
      - test-network

  faucet:
    image: faucet:latest
    links:
      - seleniumgrid:seleniumgrid
    build: faucet
    networks:
      - test-network
